---
output: github_document
---

# C.sapidus Studies - Repo Outline

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Purpose

This repository is a consolidation of code associated with the mark-recapture study of C. sapidus across the Gulf of Mexico in addition to the analysis of SEAMAP data relating to their offshore abundances.

## Data Sources

The Master data for the mark-recapture study is stored in the cloud and is still being updated as reports come in. Analyses for this repo are working off a timestamped copy. Code detailing the cleanup steps for the raw data is found in the `tagging_analyses/R/Cleanup` folder.

Data for the offshore analyses include historical data obtained from the Gulf States Marine Fisheries Commission, and biological data collected in the field. Both the timestamped data, and the results of the biological data collection are backed up on the cloud.

## Repo Struucture

There are two main branches to this repo. The first relates to the data and analyses related to the mark-recapture study. The second is related to data collected by SEAMAP or with assistance of its partner organizations. This includes fecundity estimates as well as offshore population estimates.